### ISSUE TITLE
[Feature Request] - GroundingDINOSamSegment node output different masks/segs for each identified object

### ISSUE THREAD

**Issue by alessandroperilli** [storyicon/comfyui_segment_anything#19]
I'm not even sure if this is possible, but perhaps this is something @dnl13 might be interested in implementing in his fork.

I would love to see a variant of this node with multiple masks outputs, each one spitting out a different identified object. 

For example, let's say that, given the image of a face as input, I ask to DINO to identify "mouth", "eyes", and "nose". Rather than having a single mask output that unifies these three otherwise disjoined elements, the node would have three outputs, one dedicated to the mouth mask, one to the eyes mask, and one to the nose mask.

This would allow further manipulation of the three objects in completely different ways. For example, I might decide that I want to re-render the nose as a painting, while the mouth is a photograph, and the eyes are a line art.

Eventually, these three masks would have to recombine in a single image. Not sure about that part, yet, but having the three masks is a starting point.

With this approach we could create multi-layererd images achieving a level of creativity that is not easy to obtain today.

Now. I realise that ComfyUI doesn't allow the creation of dynamic outputs, so this hypothetical node couldn't have as many outputs as defined by the user prompt. But, I would be happy to see 4 mask outputs to give users a degree of flexibility. If the user specifies 5 objects, the 5th object could be ignored or placed in a "everyhing else" mask, perhaps?

I understand that it's an ambitious idea. I thought it would be interesting to discuss.

**Comment by dnl13** [comment]
Hey @alessandroperilli,

In my fork, achieving this functionality is already somewhat possible. Take a look at this screenshot of a workflow: 
![muliti](https://github.com/storyicon/comfyui_segment_anything/assets/2972396/db4d377c-f7ff-4885-8c99-116ad73400ab)

In 'GroundingDinoSAMSegment,' simply enable the multimask feature and use the 'Batch Select' Node that I have specially built for this use case. It allows you to choose which mask or image you would like to process further.

The implementation could possibly be more user-friendly. Therefore, a bit more testing is required to optimize the nodes for this type of task.

However, be cautious of some limitations with the prompting: GroundingDino currently utilizes the bert-base-uncased model for text encoding. I am currently exploring ways to enhance this, possibly by incorporating a larger BERT model. Assistance in this area would be greatly appreciated.

I apologize for not having progressed further with the documentation and example workflows.

**Comment by alessandroperilli** [comment]
Oh, this is so good! I assume that the masks are generated in the same order the prompt order, yes? A critical aspect is knowing which is which while keeping the automation element of this.

And yes, anything you could do to expand the text encoding capabilities would be greatly appreciated. I don't have enough cycles right now to assist in active development, but I can test extensively. 

How do we get all these great features in ComfyUI Manager faster than now? :) 

Does @storyicon grant you permission to merge?

**Comment by alessandroperilli** [comment]
Daniel, I'm testing your multimask option and it's amazing. I have 2 problems, tho.

The first one is blocking: the masks generated by GroundingDINO node are not ordered according to the terms defined in the prompt.

In the following example, I'd expect to have a mask for the eyes (at batch index 1), a mask for the mouth (at batch index 2), and a mask for the hair (at batch index 3):

<img width="1078" alt="Screenshot 2023-11-19 at 19 03 48" src="https://github.com/storyicon/comfyui_segment_anything/assets/9775949/a95e79fa-370a-4191-abf6-c1a90ff18ea0">

Instead, as you can see, the hair mask comes in second position. So the part of the workflow, set for batch index 3 (where I expected to receive the hair mask, is screwed:

<img width="1130" alt="Screenshot 2023-11-19 at 19 10 48" src="https://github.com/storyicon/comfyui_segment_anything/assets/9775949/0d9bbbe4-3d65-4501-8d0a-9f3887e03f50">

I'd really need the position of the masks to be deterministic. 

The second problem is that, as you can see from the first screenshot, some detected objects generate multiple masks. If I detect "eyes", I get a mask for each eye and then a mask for both eyes. This is not a blocking problem, but only as long as I can be sure of where each mask will be positioned in the list.

Other than that, this is amazing tech. Thank you!

**Comment by dnl13** [comment]
Hey @alessandroperilli , 

yes, those are known issues that I'm currently addressing. Currently, the masks are sorted based on the model confidence, where the model was most certain, aligning with the prompt. At the moment, I still need to figure out how to handle image features that didn't receive any classes (often, I don't get a "dino_phrase" back, which is crucial for the prompt alignment).

The issue with eyes and multiple masks is also under investigation. It seems to be related to prompting. Using a high box threshold and the prompt "eyes" sometimes allows retrieving both eyes without individual masks. However, the high box threshold might lead to the non-detection of other features. I'm currently testing this. I will soon set up a new Git repo for further tests, which can then be added to the manager as well. Since I've made significant changes, I'm not sure if @storyicon wants these major modifications in his repo. 
I haven't heard from storyicon for a long time, and unfortunately, I don't know if my PR will still be accepted. That seems to be the reason for starting a new repository.
Once I have the repo online, I'll let you know.

**Comment by alessandroperilli** [comment]
Good. It makes sense to start a parallel fork to move the development forward. Let me know.

Until then, to address a couple of points:

1. I "solved" the eyes issue thanks to the `Combined` option in the `MASKS to SEGS` node. In fact, I activated it for all nodes at the same time. So, even if GroundingDINO generates multiple segments for the same identified object, I still have a single entity to deal with. It's the best option I could think of.

<img width="727" alt="Screenshot 2023-11-20 at 15 51 16" src="https://github.com/storyicon/comfyui_segment_anything/assets/9775949/86c66a9d-a835-4bd9-9e63-11b2f09e2f43">

2. The only way to circumvent the issue with the order of identified objects is by duplicating GroundingDINO nodes, which is what I'm doing now.
So, if I want to identify 4 entities and manipulate them independently, I am currently forced to have 4 instances of GroundingDINO as entry point for 4 parallel pipelines (which eventually merge back into a single image).

<img width="1452" alt="Screenshot 2023-11-20 at 15 55 08" src="https://github.com/storyicon/comfyui_segment_anything/assets/9775949/5a1df292-91c3-4486-acce-1b206cd9d5f5">

Not ideal, but not even catastrophic. It would be nice to save 3 nodes and the related computation, but it's dramatic, don't do it.
Personally, I care much more about a very granular capability of groundingDINO to identify entities. 

Looking forward to continuing the conversation on the new repo.

**Comment by dnl13** [comment]
Hello @alessandroperilli, feel free to come over; the new repository has been launched. While not all issues have been resolved yet, it marks a "fresh start" over there. 

Let's conduct thorough testing there, and once we are reasonably satisfied, we can initiate a pull request for the manager.

https://github.com/dnl13/ComfyUI-dnl13-seg
