### ISSUE TITLE
can someone guide me how to install this plugin?

### ISSUE THREAD

**Issue by jimmy8399** [storyicon/comfyui_segment_anything#22]
![image](https://github.com/storyicon/comfyui_segment_anything/assets/126844891/56b56caa-b9fb-4620-b6c7-de9d1e954da8)
when i git in UI manager its will be fail, can someone guide me how to download this?
 thanks

**Comment by jimmy8399** [comment]
![image](https://github.com/storyicon/comfyui_segment_anything/assets/126844891/a5d41ed2-9307-479d-9cef-dc44d15cd69b)
here is my comfy ui shows when im install the missing custom node , any idea? thanks alot

**Comment by jimmy8399** [comment]
im useing this flow https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/Reposer_Plus_bypass.png

**Comment by budihartono** [comment]
I suggest you to uninstall it first from ComfyUI Manager, then install it manually:
```
cd custom_nodes
git clone https://github.com/storyicon/comfyui_segment_anything
pip install -r requirements.txt
```

**Comment by storyicon** [comment]
Now dependencies will be installed automatically, and this issue should have been resolved. If you have any other problem, feel free to reopen the issue.

**Comment by rollingcookies** [comment]
> Я предлагаю вам сначала удалить его из ComfyUI Manager, а затем установить вручную:
> 
> ```
> cd custom_nodes
> git clone https://github.com/storyicon/comfyui_segment_anything
> cd comfyui_segment_anything
> pip3 install -r requirements.txt
> ```

After calling pip3 the following error occurs. And the wrong path to python.exe (underlined) is specified in the error. How to fix it and what could be the problem?
![2024-01-22_22-31-57](https://github.com/storyicon/comfyui_segment_anything/assets/40675630/4a7db733-b10a-4e64-8957-8f8d412faf58)
