### ISSUE TITLE
Request for Configurable Default Addresses in extra_model_paths.yaml

### ISSUE THREAD

**Issue by Lin1031** [storyicon/comfyui_segment_anything#28]
Can the default addresses in groundingdino_model_dir and sam_model_dir be made configurable in extra_model_paths.yaml?

Also, I encountered an issue where even though I have already downloaded the model at the specified address, it still tries to call the Hugging Face API. Is AutoTokenizer only capable of remote calls? 

![image](https://github.com/storyicon/comfyui_segment_anything/assets/44975556/717032dc-0c3e-4bbc-b379-94c5c2dab580)

**Comment by storyicon** [comment]
https://github.com/storyicon/comfyui_segment_anything/pull/31

This pull request should address and close the issue. However, as mentioned inside, many other custom nodes are modifying `folder_names_and_paths` in an incorrect way, often resulting in the invalidation of `extra_model_paths.yaml`.
