### ISSUE TITLE
GroundingDinoModelLoader (segment anything) ERROR

### ISSUE THREAD

**Issue by youcanyoubing** [storyicon/comfyui_segment_anything#35]
ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000013742FF3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
我手动下载里tf_model.h5，但是不知道要放到哪里
I downloaded the tf_model.h5 manually, but I don't know where to put it

**Comment by storyicon** [comment]
This change might address the issue you're encountering. Please check https://github.com/storyicon/comfyui_segment_anything?tab=readme-ov-file#bert-base-uncased for more information. If you have any other problem, feel free to reopen the issue.
