### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by swim2sun** [storyicon/comfyui_segment_anything#5]
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 305, in main
    (images, masks) = sam_segment(
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by swim2sun** [comment]
I think it should be caused by this line https://github.com/storyicon/comfyui_segment_anything/blob/8681365fa64fc851be621b10eff47ff2473ca1db/node.py#L217

**Comment by GoDJr** [comment]
Were you able to fix this? Ran into this issue as well.

**Comment by swim2sun** [comment]
> Were you able to fix this? Ran into this issue as well.

No, I have no idea

**Comment by GoDJr** [comment]
I fixed it on my end by decreasing the threshold. assuming everything is hooked up right. Lower the threshold to something super low like 0.05 and see if it runs. I believe what is happening is segment anything is masking the whole image. so what I did was decrease it to 0.05 and see if it ran and then slowly increase it to get the desired output.

**Comment by ttulttul** [comment]
I think the better fix would be for the module to tolerate finding "nothing". That's a reasonable result. In that case, just copy the input to the output.
