### ISSUE TITLE
Error occurred when executing GroundingDinoModelLoader (segment anything)

### ISSUE THREAD

**Issue by siboney** [storyicon/comfyui_segment_anything#75]
Hi！
When I run this node, I get this error at the "GroundingDinoModelLoader (segment anything)" node. Please tell me how to solve this problem. I tried two official models (groundingdino_swinb_cogcoor.pth, groundingdino_swint_ogc.pth) and both failed:

Error occurred when executing GroundingDinoModelLoader (segment anything):

Consistency check failed: file should be of size 440449768 but has size 79317221 (model.safetensors).

We are sorry for the inconvenience. Please retry with `force_download=True`.

If the issue persists, please let us know by opening an issue on  ......

**Comment by octadion** [comment]
bro @siboney how did you solve it
