### ISSUE TITLE
AttributeError: 'Sam' object has no attribute 'image_size'

### ISSUE THREAD

**Issue by summer379979741** [storyicon/comfyui_segment_anything#83]

**Comment by summer379979741** [comment]
After installed the plug-in "storyicon/comfyui_segment_anything" never again "https://github.com/neverbiasu/ComfyUI-SAM2)" installation, Otherwise you get an "AttributeError: 'Sam' object has no attribute 'image_size'", and it took me a day to figure out that the two plug-ins were in conflict

**Comment by emourdavid** [comment]
I have same issue: Sam' object has no attribute 'image_size'

I removed storyicon/comfyui_segment_anything and all ComfyUI-SAM2 nodes.. I reinstall storyicon/comfyui_segment_anything but issue still

**Comment by emourdavid** [comment]
I restart Comfyui and issue gone. Thanks

**Comment by thuc248997** [comment]
I removed SAM2 custom node and restart => Anything worked
